language: go

dist: bionic

os:
  - linux
  - osx
  - windows

go:
  - 1.12.x
  - 1.13.x
  - master

go_import_path: github.com/albenik/go-serial/v2

env:
  global:
    - GO111MODULE=on
    - GO386=387
    - GOARM=5
  jobs:
    - BUILD_OS=linux BUILD_ARCH=amd64
    - BUILD_OS=linux BUILD_ARCH=386
    - BUILD_OS=linux BUILD_ARCH=arm
    - BUILD_OS=windows BUILD_ARCH=386
    - BUILD_OS=windows BUILD_ARCH=amd64
    - BUILD_OS=darwin BUILD_ARCH=386
    - BUILD_OS=darwin BUILD_ARCH=amd64
    - BUILD_OS=freebsd BUILD_ARCH=amd64
    - BUILD_OS=openbsd BUILD_ARCH=amd64
    - BUILD_OS=openbsd BUILD_ARCH=386
    - BUILD_OS=openbsd BUILD_ARCH=arm

matrix:
  allow_failures:
    - env: BUILD_OS=openbsd BUILD_ARCH=arm

script:
  - go vet ./...
  - go test -v ./...
  - GOOS=$BUILD_OS GOARCH=$BUILD_ARCH go test -v -c
  - GOOS=$BUILD_OS GOARCH=$BUILD_ARCH go build -v

notifications:
  email:
    recipients:
      - albenik@gmail.com
    on_success: change
    on_failure: always
