language: go

dist: bionic

os:
  - linux
  - osx
  - windows

go:
  - 1.12.x
  - 1.13.x
  - master

go_import_path: github.com/albenik/go-serial/v2

env:
  global:
    - GO111MODULE=on
    - GO386=387
    - GOARM=5
  jobs:
    - GIMME_OS=linux GIMME_ARCH=amd64
    - GIMME_OS=linux GIMME_ARCH=386
    - GIMME_OS=linux GIMME_ARCH=arm
    - GIMME_OS=windows GIMME_ARCH=386
    - GIMME_OS=windows GIMME_ARCH=amd64
    - GIMME_OS=darwin GIMME_ARCH=386
    - GIMME_OS=darwin GIMME_ARCH=amd64
    - GIMME_OS=freebsd GIMME_ARCH=amd64
    - GIMME_OS=openbsd GIMME_ARCH=amd64
    - GIMME_OS=openbsd GIMME_ARCH=386
    - GIMME_OS=openbsd GIMME_ARCH=arm

matrix:
  allow_failures:
    - env: GIMME_OS=openbsd GIMME_ARCH=arm

script:
  - GOOS=$GOHOSTOS GOARCH=$GOHOSTARCH go test -v ./...
  - go build -v

notifications:
  email:
    recipients:
      - albenik@gmail.com
    on_success: change
    on_failure: always
