language: go

os:
  - linux
  - osx
  - windows

go:
  - 1.12.x
  - 1.13.x
  - tip

dist: bionic

go_import_path: github.com/albenik/go-serial/v2

env:
  global:
    - GO111MODULE=on
    - GOARM=5
    - GO386=387
  jobs:
    - GOOS=linux GOARCH=386
    - GOOS=linux GOARCH=amd64
    - GOOS=linux GOARCH=arm
    - GOOS=windows GOARCH=386
    - GOOS=windows GOARCH=amd64
    - GOOS=darwin GOARCH=386
    - GOOS=darwin GOARCH=amd64
    - GOOS=freebsd GOARCH=amd64
    - GOOS=openbsd GOARCH=amd64
    - GOOS=openbsd GOARCH=386
    - GOOS=openbsd GOARCH=arm

matrix:
  allow_failures:
    - env: GOOS=openbsd GOARCH=arm

script:
  - go build -v
  - go test -c -v
  - if [[ $GOOS == "linux" && ($GOARCH == "386" || $GOARCH == "amd64") ]]; then go test -v ./...; fi


notifications:
  email:
    recipients:
      - albenik@gmail.com
    on_success: change
    on_failure: always
